# Generated by Django 6.0.4 on 2026-05-13 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='store',
            field=models.ForeignKey(blank=True, help_text='ユーザーが所属する店舗', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='stores.store', verbose_name='店舗'),
        ),
    ]
