# Generated by Django 6.0.4 on 2026-05-13 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('store_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='店舗ID')),
                ('business_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='事業者番号')),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='代表者名')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='住所')),
                ('telephone', models.CharField(max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('business_hours', models.CharField(blank=True, help_text='例: 11:00-22:00', max_length=20, null=True, verbose_name='営業時間')),
                ('closed_days', models.CharField(blank=True, help_text='例: 毎週水曜日', max_length=20, null=True, verbose_name='定休日')),
                ('table_count', models.PositiveIntegerField(help_text='例: 10', verbose_name='テーブル数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_store', to=settings.AUTH_USER_MODEL, verbose_name='オーナー')),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
                'db_table': 'stores',
                'ordering': ['-created_at'],
            },
        ),
    ]
