# Generated by Django 6.0.4 on 2026-05-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(help_text='例: 1, 2, A1, B2など', max_length=10, verbose_name='テーブル番号')),
                ('table_type', models.CharField(blank=True, help_text='例: 2人用, 4人用, カウンター', max_length=30, null=True, verbose_name='テーブルタイプ')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='位置')),
                ('qr_code_url', models.URLField(blank=True, max_length=250, null=True, verbose_name='QRコードURL')),
                ('max_seats', models.PositiveIntegerField(blank=True, null=True, verbose_name='最大人数')),
                ('status', models.CharField(choices=[('vacant', '空席'), ('occupied', '使用中'), ('reserved', '予約済み')], default='vacant', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='stores.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'テーブル',
                'verbose_name_plural': 'テーブル一覧',
                'ordering': ['table_number'],
                'unique_together': {('store', 'table_number')},
            },
        ),
    ]
