# Generated by Django 6.0.4 on 2026-05-21 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_storetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリー名')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='英文名')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('icon_image_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='アイコン画像URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='stores.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'メニューカテゴリー',
                'verbose_name_plural': 'メニューカテゴリー一覧',
                'ordering': ['display_order', 'name'],
                'unique_together': {('store', 'name')},
            },
        ),
    ]
