# Generated by Django 6.0.4 on 2026-05-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_menucategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together={('store', 'display_order')},
        ),
    ]
