# Generated by Django 6.0.4 on 2026-05-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_menucategory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together={('store', 'name')},
        ),
    ]
