# Generated by Django 6.0.4 on 2026-05-25 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_menucategory_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='メニュー名')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='価格')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('allergy_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='アレルギー情報')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='代表イメージURL')),
                ('is_available', models.BooleanField(default=True, verbose_name='販売可否')),
                ('is_sold_out', models.BooleanField(default=False, verbose_name='売切状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='stores.menucategory', verbose_name='カテゴリー')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='stores.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': ('メニュー',),
                'verbose_name_plural': ('メニュー一覧',),
                'ordering': ['category__display_order', 'name'],
            },
        ),
    ]
