# Generated by Django 6.0.4 on 2026-05-26 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='グループ名')),
                ('selection_type', models.CharField(choices=[('single', '単一選択'), ('multiple', '複数選択')], default='single', max_length=10, verbose_name='選択方法')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='stores.menu', verbose_name='対象メニュー')),
            ],
            options={
                'verbose_name': 'メニューオプショングループ',
                'verbose_name_plural': 'メニューオプショングループ一覧',
                'ordering': ['menu', 'name'],
            },
        ),
    ]
