# Generated by Django 6.0.4 on 2026-06-01 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_menuoptiongroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['category__display_order', 'name'], 'verbose_name': 'メニュー', 'verbose_name_plural': 'メニュー一覧'},
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='オプション名')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='英文名')),
                ('additional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='追加価格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('menu_option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='stores.menuoptiongroup', verbose_name='オプショングループ')),
            ],
            options={
                'verbose_name': 'オプション項目',
                'verbose_name_plural': 'オプション項目一覧',
                'ordering': ['menu_option_group', 'name'],
            },
        ),
    ]
